practice5/recipe_project/recipe_catalog/urls.py
from django.contrib.auth import views
from django.urls import path, include
from .views import (
	recipe_detail,
	index,
	about,
	form_user_test,
	login_view,
	custom_logout,register,
	ingredient_list,
	add_ingredient,
	delete_ingredient,
	update_ingredient
)

app_name = 'recipe_catalog'

urlpatterns = [
	path('', index, name='index'),
    path('recipe/<int:pk>/', recipe_detail, name='recipe_detail'),
	path('about/', about, name='about'),
	path('user_form_test/', form_user_test, name='user_form_test'),
	path('login/', views.LoginView.as_view(template_name='recipe_catalog/login.html'), name='login'),  # Страница логина
	path('logout/', custom_logout, name='logout'),
	path('register/', register, name='register'),

	path('ingredients/', ingredient_list, name='ingredient_list'),
    path('ingredient/add/', add_ingredient, name='add_ingredient'),
	path('ingredient/delete/<int:pk>/', delete_ingredient, name='delete_ingredient'),
    path('ingredient/update/<int:pk>/', update_ingredient, name='update_ingredient'),
]

practice5/recipe_project/recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe_catalog.urls')),
]

practice5/recipe_project/recipe_catalog/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, RegexValidator
from django.db import models

User = get_user_model()

class MeasureUnit(models.Model):
    name = models.CharField(
		max_length=255,
        verbose_name='Полное название единицы измерения',
		validators=[
			RegexValidator(
				regex=r'^[A-Za-zА-Яа-яёЁ\s]+$',
				message='Название должно быть текстом'
			)
		]
	)
    short_name = models.CharField(
        max_length=20,
        verbose_name='Краткая форма единицы измерения'
    )
    grams_in_unit = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Количество грамм в единице измерения',
        validators=[
            MinValueValidator(
                limit_value=1,
                message='Вес должен быть не меньше 1'
            )
        ]
    )

    def __str__(self):
        return f"{self.name} ({self.short_name}) - равен {self.grams_in_unit} грамм"


class Ingredient(models.Model):
    """Составная часть рецепта"""
    name = models.CharField(
		max_length=255,
		validators=[
			RegexValidator(
				regex=r'^[A-Za-zА-Яа-яёЁ\s]+$',
				message='Название должно быть текстом'
			)
		]
	)
    measure_unit = models.ForeignKey(
        MeasureUnit,
        on_delete=models.CASCADE,
        verbose_name='Единица измерения'
    )
    amount = models.IntegerField(
        verbose_name="Количество в единицах измерения",
        validators=[
            MinValueValidator(
                limit_value=1,
                message='Количество должно быть не больше 1'
            )
        ]
    )
    cost = models.FloatField(
        # null=True,
        validators=[
            MinValueValidator(
                limit_value=1,
                message='Цена должна быть не меньше 1 рубля'
            )
        ]
    )
    author = models.ForeignKey(
        User,
        verbose_name='Создатель ингредиента',
        on_delete=models.CASCADE, null=True
    )

    @property
    def weight(self):
        if self.measure_unit:
            return self.amount * self.measure_unit.grams_in_unit
        return 0

    def __str__(self):
        return (f'{self.name} - {self.amount} {self.measure_unit.short_name}- {self.weight} {self.author} '
                f'{self.measure_unit.short_name}')

class Recipe(models.Model):
    """Вкусное делается по рецепту"""
    name = models.CharField(
		max_length=300,
		validators=[
			RegexValidator(
				regex=r'^[A-Za-zА-Яа-яёЁ\s]+$',
				message='Название должно быть текстом'
			)
		]
	)
    ingredients = models.ManyToManyField(
        Ingredient, through="RecipeIngredient")
    author = models.ForeignKey(
        User,
        verbose_name='Автор рецепта',
        on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return self.name

class RecipeIngredient(models.Model):
    """Один ингредиент может быть в нескольких рецептах,
    как и в одном рецепте может быть
    несколько ингредиентов."""

    recipe = models.ForeignKey(
        Recipe, on_delete = models.CASCADE)
    ingredient = models.ForeignKey(
    Ingredient, on_delete = models.CASCADE)

    def __str__(self):
        return f'{self.recipe.name} - {self.ingredient.name}'

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['recipe', 'ingredient'],
                name='unique ingredients for receipt'
            )
        ]

practice5/recipe_project/recipe_catalog/forms.py
from django.contrib.auth import get_user, get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Ingredient, Recipe


User = get_user_model()

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name', 'measure_unit', 'amount', 'cost']  # Укажите нужные поля
        labels = {
            'name': 'Название ингредиента',
            'measure_unit': 'Единица измерения',
            'amount': 'Количество',
            'cost': 'Стоимость',
        }
        help_texts = {
            'name': 'Введите название ингредиента (например, "Мука").',
            'measure_unit': 'Выберите единицу измерения для ингредиента.',
            'amount': 'Укажите количество в выбранных единицах измерения.',
            'cost': 'Укажите стоимость указанного количества.',
        }
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Например, Куриное филе',
            }),
            'measure_unit': forms.Select(attrs={
                'class': 'form-select',
            }),
            'amount': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Например, 500',
            }),
            'cost': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Например, 200.00',
            }),
        }


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'ingredients']  # Укажите нужные поля
        labels = {
            'name': 'Название рецепта',
            'ingredients': 'Ингредиенты',
        }
        help_texts = {
            'name': 'Введите название рецепта (например, "Гирос").',
            'ingredients': 'Выберите ингредиенты для рецепта.',
        }
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Например, Гирос',
            }),
            'ingredients': forms.SelectMultiple(attrs={
                'class': 'form-control',
            }),
        }

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

practice5/recipe_project/recipe_catalog/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from .forms import CustomUserCreationForm, IngredientForm
from .models import Recipe, Ingredient


def about(request):
    return render(request, 'recipe_catalog/about.html')

def index(request):
    template_name = 'recipe_catalog/index2.html'
    recipes = Recipe.objects.all()
    return render(request, template_name, {'recipes': recipes})

def recipe_detail(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)
    ingredients = recipe.ingredients.select_related('measure_unit').all()

    # Рассчитываем общую стоимость рецепта
    total_cost = sum(ingredient.cost for ingredient in ingredients)

    # Рассчитываем общий вес рецепта
    total_weight = sum(ingredient.weight for ingredient in ingredients)

    return render(request, 'recipe_catalog/recipe_detail.html', {
        'recipe': recipe,
        'ingredients': ingredients,
        'cost': total_cost,
        'weight': total_weight,
    })

def form_user_test(request):
    template_name = 'recipe_catalog/user_form_test.html'
    if request.GET:
        form = UserCreationForm(request.GET)
        print(form)
        if form.is_valid():
            pass
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, template_name, context)


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')  # Перенаправление на главную страницу или любую другую
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})

def custom_logout(request):
    logout(request)  # Завершаем сессию пользователя
    # Дополнительные действия, например, вывод сообщения
    return redirect('/')  # Перенаправление на главную страницу или на другую

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('recipe_catalog:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'recipe_catalog/register.html', {'form': form})

@login_required
def ingredient_list(request):
    template_name = 'recipe_catalog/ingredients_list.html'
    ingredients = Ingredient.objects.all()
    return render(request, template_name, {'ingredients': ingredients})

def add_ingredient(request):
    template = 'recipe_catalog/add_ingredient.html'
    form = IngredientForm(request.POST or None)
    if form.is_valid():
        ingredient = form.save(commit=False)
        ingredient.author = request.user
        ingredient.save()
        messages.success(request, 'Ингредиент был успешно добавлен')
        return redirect('recipe_catalog:ingredient_list')
    context = {'form': form}
    return render(request, template, context)


@login_required
def delete_ingredient(request, pk):
    ingredient = get_object_or_404(Ingredient, pk=pk)

    if request.user == ingredient.author:
        ingredient.delete()
        return redirect('recipe_catalog:ingredient_list')
    else:
        return redirect('recipe_catalog:ingredient_list')

@login_required
def update_ingredient(request, pk):
    instance = get_object_or_404(Ingredient, pk=pk)
    if request.user != instance.author:
        raise PermissionDenied("Вы не можете редактировать этот ингредиент")
    form = IngredientForm(request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        return redirect('recipe_catalog:ingredient_list')
    context = {'form': form}
    return render(request, 'recipe_catalog/update_ingredient.html', context)

practice5/recipe_project/templates/recipe_catalog/about.html
{% extends "base.html" %}

{% block title %}О нас - Рецептор{% endblock %}

{% block content %}
<h2 class="my-4">О нашем проекте</h2>
<p class="lead">Добро пожаловать на сайт "Рецептор" — ваш надежный источник вкусных и разнообразных кулинарных идей!</p>
{% endblock %}

practice5/recipe_project/templates/recipe_catalog/add_ingredient.html
{% extends 'base.html' %}

{% block content %}
<main class="container">
    <h2 class="my-4">Добавить ингредиент</h2>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Добавить ингредиент</button>
    </form>
</main>
{% endblock %}

practice5/recipe_project/templates/recipe_catalog/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная - Рецепты</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .recipe-item {
            padding: 10px;
            margin-bottom: 10px;
            background-color: #343a40;
            border: 1px solid #495057;
            border-radius: 5px;
        }
        .recipe-item a {
            color: #f8f9fa;
            text-decoration: none;
        }
        .recipe-item:hover {
            background-color: #495057;
        }
    </style>
</head>
<body class="bg-dark text-white">
<header class="bg-dark text-light py-3">
    <div class="container d-flex justify-content-between align-items-center">
        <h2 class="mb-0">Рецептор</h2>
        <nav>
            <a href="/" class="btn btn-primary mx-2">Главная</a>
            <a href="/about" class="btn btn-secondary mx-2">О нас</a>
        </nav>
    </div>
</header>

<main class="container">
    <h2 class="my-4">Все рецепты</h2>
    <div class="list-group">
        {% for recipe in recipes %}
        <div class="recipe-item">
            <a href="{% url 'recipe_detail' recipe.id %}">{{ recipe.name }}</a>
        </div>
        {% empty %}
        <div class="recipe-item">
            Нет рецептов
        </div>
        {% endfor %}
    </div>
</main>

<footer class="bg-dark text-light py-4">
    <div class="container text-center">
        <p>&copy; 2024 Рецепты. Все права защищены.</p>
    </div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</body>
</html>

practice5/recipe_project/templates/recipe_catalog/index2.html
{% extends "base.html" %}

{% block title %}Главная - Рецептор{% endblock %}

{% block content %}
<h2 class="my-4">Все рецепты</h2>
    <div class="list-group">
        {% for recipe in recipes %}
        <div class="recipe-item">
            <a href="{% url 'recipe_catalog:recipe_detail' recipe.id %}">{{ recipe.name }}</a>
        </div>
        {% empty %}
        <div class="recipe-item">
            Нет рецептов
        </div>
        {% endfor %}
    </div>
{% endblock %}

practice5/recipe_project/templates/recipe_catalog/ingredient_form.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить ингредиент - Рецептор</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .form-container {
            background-color: #343a40;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        }
    </style>
</head>
<body class="bg-dark text-white">
<header class="bg-dark text-light py-3">
    <div class="container d-flex justify-content-between align-items-center">
        <h2 class="mb-0">Добавить ингредиент</h2>
        <nav>
            <a href="/" class="btn btn-primary mx-2">Главная</a>
            <a href="/about" class="btn btn-secondary mx-2">О нас</a>
        </nav>
    </div>
</header>

<main class="container">
    <div class="my-4">
        <h2>Форма ингредиента</h2>
        <div class="form-container">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary mt-3">Сохранить</button>
            </form>
        </div>
    </div>
</main>

<footer class="bg-dark text-light py-4">
    <div class="container text-center">
        <p>&copy; 2024 Рецептор. Все права защищены.</p>
    </div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</body>
</html>

practice5/recipe_project/templates/recipe_catalog/ingredients_list.html
{% extends 'base.html' %}

{% block content %}
<main class="container">
    <h2 class="my-4">Все ингредиенты</h2>

    {% if user.is_authenticated %}
        <div class="mb-3">
            <a href="{% url 'recipe_catalog:add_ingredient' %}" class="btn btn-success">Добавить ингредиент</a>
        </div>
    {% endif %}

    <div class="list-group">
        {% for ingredient in ingredients %}
            <div class="ingredient-item">
                <p>{{ ingredient.name }} - {{ ingredient.amount }} {{ ingredient.measure_unit.short_name }} ({{ ingredient.weight }} г)</p>
                {% if user.is_authenticated and ingredient.author == user %}
                    <a href="{% url 'recipe_catalog:update_ingredient' ingredient.pk  %}" class="btn btn-warning">Редактировать</a>
                    <a href="{% url 'recipe_catalog:delete_ingredient' ingredient.pk %}" class="btn btn-warning">Удалить</a>
                {% endif %}
            </div>
        {% empty %}
            <div class="ingredient-item">
                Нет ингредиентов
            </div>
        {% endfor %}
    </div>
</main>
{% endblock %}

practice5/recipe_project/templates/recipe_catalog/login.html
{% extends "base.html" %}

{% block title %}Вход - Рецепты{% endblock %}

{% block content %}
<h2 class="my-4">Вход в систему</h2>

<form method="post" action="/login/" class="login-form">
    {% csrf_token %}
    <table class="login-table">
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>
    <div class="form-actions">
        <input type="submit" value="Войти" class="btn-submit">
        <input type="hidden" name="next" value="/">
    </div>
</form>

{% endblock %}

practice5/recipe_project/templates/recipe_catalog/recipe_detail.html
{% extends "base.html" %}

{% block title %}{{ recipe.name }} - Рецепты{% endblock %}

{% block content %}
<h2 class="my-4">{{ recipe.name }}</h2>

<h4>Ингредиенты:</h4>
<ul>
    {% for ingredient in ingredients %}
    <li>
        {{ ingredient.name }} - {{ ingredient.amount }} {{ ingredient.measure_unit.short_name }}
    </li>
    {% empty %}
    <li>Нет ингредиентов</li>
    {% endfor %}
</ul>

<h4>Стоимость и вес:</h4>
<p>Общая стоимость: {{ cost }} руб.</p>
<p>Общий вес: {{ weight }} руб.</p>

{% endblock %}

practice5/recipe_project/templates/recipe_catalog/recipe_form.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить рецепт - Рецептор</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .form-container {
            background-color: #343a40;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        }
    </style>
</head>
<body class="bg-dark text-white">
<header class="bg-dark text-light py-3">
    <div class="container d-flex justify-content-between align-items-center">
        <h2 class="mb-0">Добавить рецепт</h2>
        <nav>
            <a href="/" class="btn btn-primary mx-2">Главная</a>
            <a href="/about" class="btn btn-secondary mx-2">О нас</a>
        </nav>
    </div>
</header>

<main class="container">
    <div class="my-4">
        <h2>Форма рецепта</h2>
        <div class="form-container">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary mt-3">Сохранить</button>
            </form>
        </div>
    </div>
</main>

<footer class="bg-dark text-light py-4">
    <div class="container text-center">
        <p>&copy; 2024 Рецептор. Все права защищены.</p>
    </div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</body>
</html>

practice5/recipe_project/templates/recipe_catalog/register.html
{% extends "base.html" %}

{% block title %}Главная - Рецептор{% endblock %}

{% block content %}
<h2 class="my-4">Создайте аккаунт</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Имя пользователя</label>
            <input type="text" name="username" class="form-control" id="id_username" required placeholder="Введите имя пользователя">
        </div>
        <div class="form-group">
            <label for="id_email">Email</label>
            <input type="email" name="email" class="form-control" id="id_email" required placeholder="Введите email">
        </div>
        <div class="form-group">
            <label for="id_password1">Пароль</label>
            <input type="password" name="password1" class="form-control" id="id_password1" required placeholder="Введите пароль">
        </div>
        <div class="form-group">
            <label for="id_password2">Повторите пароль</label>
            <input type="password" name="password2" class="form-control" id="id_password2" required placeholder="Повторите пароль">
        </div>
        <button type="submit" class="btn btn-primary mt-3">Зарегистрироваться</button>
    </form>
{% endblock %}

practice5/recipe_project/templates/recipe_catalog/update_ingredient.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Обновить ингредиент</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
        <a href="{% url 'recipe_catalog:ingredient_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

practice5/recipe_project/templates/recipe_catalog/user_form_test.html
<!-- A common form that includes input tags -->
<form action="getform.php" method="post">
 First name: <input type="text" name="first_name" /><br />
 Last name: <input type="text" name="last_name" /><br />
 E-mail: <input type="email" name="user_email" /><br />
 <input type="submit" value="Submit" />
</form>